import EventList from "../components/events/EventList";
import { useState, useEffect } from "react";

// const DUMMY_EVENTS = [
//   {
//     id: "e1",
//     title: "CMU Career Fair",
//     description: "CMU Career Fair 2023",
//     location: "CMU",
//     image: "https://live.staticflickr.com/589/32880578552_1eddf34d90_b.jpg",
//   },
//   {
//     id: "e2",
//     title: "Basketball Game",
//     description: "2023, CMU basketball game",
//     location: "at CMU",
//     image:
//       "https://athletics.cmu.edu/sports/mbkb/2022-23/photos/emory/cmuMBBvsEmory-Highlights-8.jpg",
//   },
// ];

function AllEventsPage() {
  const [isLoading, setIsLoading] = useState(true);
  // overwrite the data
  const [loadedEvents, setLoadedEvents] = useState([]);

  // Prevent the page from reloading
  useEffect(() => {
    console.log("Visit All Events Page, Now")
    setIsLoading(true);
    fetch(
      "https://react-memory-app-f1cdb-default-rtdb.firebaseio.com/events.json"
    )
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        setIsLoading(false);
        const events = [];
        for (const key in data) {
          const event = {
            id: key,      // auto-generated by Firebase
            ...data[key], // spread operator
          };
          events.push(event);
        }
        setLoadedEvents(events );
      });
  }, []); // second argument is dependency, should include all external values Effect relies on

  if (isLoading) {
    return (
      <section>
        <p>Loading...</p>
      </section>
    );
  }

  return (
    <section>
      <h1>All Events</h1>
      <EventList events={loadedEvents} />
    </section>
  );
}

export default AllEventsPage;
