import EventList from "../components/upcomingEvents/EventList";
import { useState, useEffect } from "react";


function AllEventsPage() {
  const [isLoading, setIsLoading] = useState(true);
  // overwrite the data
  const [loadedEvents, setLoadedEvents] = useState([]);

  // Prevent the page from reloading
  useEffect(() => {
    console.log("Visit All Events Page, Now")

    setIsLoading(true);
    fetch(
      process.env.REACT_APP_FIREBASE_API_KEY + "/events.json"
    )
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        setIsLoading(false);
        const events = [];
        for (const key in data) {
          const event = {
            id: key,      // auto-generated by Firebase
            ...data[key], // spread operator
          };
          events.push(event);
        }
        setLoadedEvents(events);
      });
  }, []); // second argument is dependency, should include all external values Effect relies on

  if (isLoading) {
    return (
      <section>
        <p>Loading...</p>
      </section>
    );
  }

  return (
    <section>
      <h1>All Events</h1>
      <EventList events={loadedEvents} />
    </section>
  );
}

export default AllEventsPage;
